language:
  - python

python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script: 
  - coverage run --append --include='blockchain_parser/*' --omit='*/tests/*' setup.py test

after_success:
  - if [[ $ENV == python=3.4* ]]; then
          coveralls;
    fi
